name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Cache ivy
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-ivy-cache-

      - name: Cache coursier
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-sbt-coursier-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-coursier-cache-

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sbt-cache-

      - name: Check format
        run: sbt checkAll > result.txt && grep -E '\[warn\]' result.txt > warnings.txt 

      - name: Run tests
        run: sbt test

      - name: Upload warnings.txt
        uses: actions/upload-artifact@master
        with:
          name: warnings
          path: warnings.txt

  notify:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Notify to Typetalk if success
        if: success()
        uses: shomatan/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 54145
          message: ":tada: Backlog migration common job success :smile:\n${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"

      - name: Notify to Typetalk if fail
        if: failure()
        uses: shomatan/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 54145
          message: ":rage: Backlog migration common job failed\n${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"

      - name: Notify to Typetalk if cancelled
        if: cancelled()
        uses: shomatan/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 54145
          message: ":no_entry: Backlog migration common job cancelled\n${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"

